# 1. Create a 3x3x3 array with random values.

In [1]:
import numpy as np

# Create a 3x3x3 array with random values between 0 and 1
random_array = np.random.rand(3, 3, 3)

print(random_array)

[[[0.9396838  0.4660209  0.2737508 ]
  [0.53417871 0.87148865 0.87065091]
  [0.87446435 0.3587777  0.90899988]]

 [[0.44054102 0.06640648 0.89922796]
  [0.7112502  0.98884859 0.32114963]
  [0.04872252 0.9202188  0.55374118]]

 [[0.08935243 0.62482715 0.10757629]
  [0.5576349  0.082017   0.15679268]
  [0.13626825 0.23886754 0.42519526]]]


# 2. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
import numpy as np

# Create a 5x5 matrix filled with zeros
matrix = np.zeros((5, 5))

# Fill the values 1, 2, 3, 4 just below the diagonal
np.fill_diagonal(matrix[1:], [1, 2, 3, 4])

print(matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


# 3. Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
import numpy as np

# Create an 8x8 matrix filled with zeros
matrix = np.zeros((8, 8), dtype=int)

# Fill the matrix with the checkerboard pattern
matrix[1::2, ::2] = 1  # Rows 2, 4, 6 (indexing starts from 0) and alternate columns
matrix[::2, 1::2] = 1  # Rows 1, 3, 5 and alternate columns

# Print the checkerboard pattern
for row in matrix:
    print(" ".join(map(str, row)))

0 1 0 1 0 1 0 1
1 0 1 0 1 0 1 0
0 1 0 1 0 1 0 1
1 0 1 0 1 0 1 0
0 1 0 1 0 1 0 1
1 0 1 0 1 0 1 0
0 1 0 1 0 1 0 1
1 0 1 0 1 0 1 0


# 4. Normalize a 5x5 random matrix

In [4]:
import numpy as np

# Create a 5x5 random matrix
random_matrix = np.random.rand(5, 5)

# Normalize the matrix
normalized_matrix = (random_matrix - np.mean(random_matrix)) / np.std(random_matrix)

print("Original Matrix:")
print(random_matrix)

print("\nNormalized Matrix:")
print(normalized_matrix)

Original Matrix:
[[0.40301597 0.91658224 0.8695411  0.04167214 0.15667189]
 [0.52012076 0.68455123 0.3544044  0.77541043 0.02568465]
 [0.57606354 0.34401363 0.82299998 0.33329301 0.28546371]
 [0.19940117 0.27440799 0.14694591 0.00185364 0.74955479]
 [0.30795661 0.32363823 0.22803072 0.93185443 0.19660557]]

Normalized Matrix:
[[-0.05516244  1.74085644  1.57634643 -1.31883643 -0.91666493]
 [ 0.35437069  0.92940892 -0.22516446  1.24715726 -1.37474711]
 [ 0.55001104 -0.26150257  1.41358513 -0.29899417 -0.46626049]
 [-0.7672342  -0.504924   -0.95067818 -1.45808777  1.1567362 ]
 [-0.38759941 -0.33275839 -0.66711233  1.79426559 -0.77701084]]


# 5. How to find common values between two arrays?

In [5]:
import numpy as np

# Create two arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

# Find common values between the two arrays
common_values = np.intersect1d(array1, array2)

print(common_values)


[3 4 5]


# 6. How to get the dates of yesterday, today and tomorrow?

In [6]:
from datetime import datetime, timedelta

# Get today's date
today = datetime.now()

# Calculate yesterday's date by subtracting one day
yesterday = today - timedelta(days=1)

# Calculate tomorrow's date by adding one day
tomorrow = today + timedelta(days=1)

# Format the dates as strings (optional)
today_str = today.strftime('%Y-%m-%d')
yesterday_str = yesterday.strftime('%Y-%m-%d')
tomorrow_str = tomorrow.strftime('%Y-%m-%d')

# Print the dates
print("Yesterday:", yesterday_str)
print("Today:", today_str)
print("Tomorrow:", tomorrow_str)


Yesterday: 2023-09-20
Today: 2023-09-21
Tomorrow: 2023-09-22


# 7. Consider two random array A and B, check if they are equal

In [7]:
import numpy as np

# Create two random arrays A and B
A = np.random.rand(5, 5)
B = np.random.rand(5, 5)

# Check if the arrays are equal element-wise
elementwise_equal = (A == B).all()

if elementwise_equal:
    print("Arrays A and B are equal element-wise.")
else:
    print("Arrays A and B are not equal element-wise.")


Arrays A and B are not equal element-wise.


# 8. Create random vector of size 10 and replace the maximum value by 0

In [8]:
import numpy as np

# Create a random vector of size 10
random_vector = np.random.rand(10)

# Find the index of the maximum value in the vector
max_index = np.argmax(random_vector)

# Replace the maximum value with 0
random_vector[max_index] = 0

print("Original random vector:")
print(random_vector)

Original random vector:
[0.46119612 0.41752701 0.         0.40620961 0.29274052 0.06429424
 0.28399008 0.31558109 0.69935787 0.65551941]


# 9. How to print all the values of an array?

In [9]:
#List:

my_list = [1, 2, 3, 4, 5]

for value in my_list:
    print(value)


1
2
3
4
5


In [10]:
#Using a list comprehension:

my_list = [1, 2, 3, 4, 5]
[print(value) for value in my_list]


1
2
3
4
5


[None, None, None, None, None]

In [11]:
#NumPy Array:
import numpy as np

my_array = np.array([1, 2, 3, 4, 5])
print(my_array)

[1 2 3 4 5]


In [12]:
#Pandas Series:
import pandas as pd

my_series = pd.Series([1, 2, 3, 4, 5])
print(my_series)

0    1
1    2
2    3
3    4
4    5
dtype: int64


# 10.Subtract the mean of each row of a matrix 

In [13]:
import numpy as np

# Create a sample matrix (replace this with your own matrix)
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Calculate the mean of each row
row_means = np.mean(matrix, axis=1, keepdims=True)

# Subtract the row means from the original matrix
normalized_matrix = matrix - row_means

print("Original Matrix:")
print(matrix)

print("\nMatrix with Row Means Subtracted:")
print(normalized_matrix)

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix with Row Means Subtracted:
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


# 11. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [14]:
import numpy as np

# Your initial vector
initial_vector = np.array([1, 2, 3, 4, 5])

# Second vector containing indices
indices = np.array([0, 2, 3])

# Create a new vector to store the results
result_vector = initial_vector.copy()

# Add one to each element at the specified indices
result_vector[indices] += 1

print(result_vector)

[2 2 4 5 5]


# 12.How to get the diagonal of a dot product?

In [15]:
import numpy as np

# Create two matrices A and B
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Calculate the dot product of A and B
dot_product = np.dot(A, B)

# Get the diagonal elements of the dot product
diagonal = np.diagonal(dot_product)

print(diagonal)

[30 69 90]


# 13. How to find the most frequent value in an array?

In [16]:
import numpy as np

# Sample array
my_array = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5])

# Use the `unique` function to get unique values and their counts
unique_values, counts = np.unique(my_array, return_counts=True)

# Find the index of the maximum count, which corresponds to the most frequent value
most_frequent_index = np.argmax(counts)

# Get the most frequent value
most_frequent_value = unique_values[most_frequent_index]

print(f"The most frequent value is {most_frequent_value} with {counts[most_frequent_index]} occurrences.")

The most frequent value is 4 with 4 occurrences.


# 14. How to get the n largest values of an array

In [17]:
import numpy as np

# Create an example array
arr = np.array([5, 2, 8, 1, 7, 3])

# Set the value of 'n' to get the n-largest values
n = 3

# Use partition to get the n-largest values
n_largest = np.partition(arr, -n)[-n:]

print(n_largest)

[5 7 8]


# 15. How to create a record array from a regular array?

In [18]:
import numpy as np

# Create a regular array with data
regular_array = np.array([(1, 'Alice', 25),
                           (2, 'Bob', 30),
                           (3, 'Charlie', 22)],
                          dtype=[('ID', int), ('Name', 'U10'), ('Age', int)])

# Create a record array
record_array = np.rec.fromarrays(regular_array.T, names=regular_array.dtype.names)

# Print the record array
print(record_array)

((1, 'Alice', 25), (2, 'Bob', 30), (3, 'Charlie', 22))


# 16. How to swap two rows of an array?

In [19]:
import numpy as np

# Create a sample 2D NumPy array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Swap rows (for example, swapping rows 0 and 2)
array[[0, 2]] = array[[2, 0]]

# Now, 'array' will have rows 0 and 2 swapped
print(array)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


# 17. Write python code to reshape to the next dimension of numpy array?

In [20]:
import numpy as np

# Create a NumPy array
original_array = np.array([[1, 2], [3, 4], [5, 6]])

# Reshape the array to the next dimension
reshaped_array = original_array.reshape(-1, original_array.shape[0])

# Print the original and reshaped arrays
print("Original Array:")
print(original_array)

print("\nReshaped Array:")
print(reshaped_array)

Original Array:
[[1 2]
 [3 4]
 [5 6]]

Reshaped Array:
[[1 2 3]
 [4 5 6]]
