In [1]:
import pandas as pd

# Load the dataset
df = pd.read_csv('abcnews-date-text.csv')

# Explore the first few rows to understand the data
print(df.head())

# Check the unique topics/categories
unique_topics = df['headline_text'].unique()
print("Unique Topics: ", unique_topics)

# Check the distribution of articles across topics
topic_distribution = df['headline_text'].value_counts()
print("Topic Distribution: \n", topic_distribution)

   publish_date                                      headline_text
0      20030219  aba decides against community broadcasting lic...
1      20030219     act fire witnesses must be aware of defamation
2      20030219     a g calls for infrastructure protection summit
3      20030219           air nz staff in aust strike for pay rise
4      20030219      air nz strike to affect australian travellers
Unique Topics:  ['aba decides against community broadcasting licence'
 'act fire witnesses must be aware of defamation'
 'a g calls for infrastructure protection summit' ...
 'wa delays adopting new close contact definition'
 'western ringtail possums found badly dehydrated in heatwave'
 'what makes you a close covid contact here are the new rules']
Topic Distribution: 
 headline_text
national rural news                                            983
abc sport                                                      718
abc weather                                                    714
abc busin

In [ ]:
BOW-Bag of words

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
text=['aba decides against community broadcasting licence','act fire witnesses must be aware of defamation',
      'ambitious olsson wins triple jump']
#Initialize the vector
vectorizer=CountVectorizer()
#transform
x=vectorizer.fit_transform(text)
#get feature names(words)
feature_names=vectorizer.get_feature_names_out()
#Display BOW-Matrix
print('Feature names:\n',feature_names)
print()
print('BOW Matrix:\n')
print(x.toarray())

Feature names:
 ['aba' 'act' 'against' 'ambitious' 'aware' 'be' 'broadcasting' 'community'
 'decides' 'defamation' 'fire' 'jump' 'licence' 'must' 'of' 'olsson'
 'triple' 'wins' 'witnesses']

BOW Matrix:

[[1 0 1 0 0 0 1 1 1 0 0 0 1 0 0 0 0 0 0]
 [0 1 0 0 1 1 0 0 0 1 1 0 0 1 1 0 0 0 1]
 [0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 1 1 0]]


In [ ]:
TF-IDF

In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer
text=['aba decides against community broadcasting licence','act fire witnesses must be aware of defamation',
      'ambitious olsson wins triple jump']

tfidf=TfidfVectorizer()
x_tfidf=tfidf.fit_transform(text)

features_names_tfidf=tfidf.get_feature_names_out()

print('Feature Names(TF-IDF):\n',features_names_tfidf)
print()
print('TF-IDF Matrix:\n',x_tfidf.toarray())

Feature Names(TF-IDF):
 ['aba' 'act' 'against' 'ambitious' 'aware' 'be' 'broadcasting' 'community'
 'decides' 'defamation' 'fire' 'jump' 'licence' 'must' 'of' 'olsson'
 'triple' 'wins' 'witnesses']

TF-IDF Matrix:
 [[0.40824829 0.         0.40824829 0.         0.         0.
  0.40824829 0.40824829 0.40824829 0.         0.         0.
  0.40824829 0.         0.         0.         0.         0.
  0.        ]
 [0.         0.35355339 0.         0.         0.35355339 0.35355339
  0.         0.         0.         0.35355339 0.35355339 0.
  0.         0.35355339 0.35355339 0.         0.         0.
  0.35355339]
 [0.         0.         0.         0.4472136  0.         0.
  0.         0.         0.         0.         0.         0.4472136
  0.         0.         0.         0.4472136  0.4472136  0.4472136
  0.        ]]


In [2]:
import nltk
nltk.download('punkt')

[nltk_data] Error loading punkt: <urlopen error [WinError 10060] A
[nltk_data]     connection attempt failed because the connected party
[nltk_data]     did not properly respond after a period of time, or
[nltk_data]     established connection failed because connected host
[nltk_data]     has failed to respond>


False

In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.tokenize import sent_tokenize
text=input('Enter a statement:\n\t')
sent_token=sent_tokenize(text)
#print('Sentences:\n',sent_token)
for sent in sent_token:
    print(sent)
    print(len(sent))

print()
tfidf=TfidfVectorizer()
x_tfidf=tfidf.fit_transform(sent_token)

features_names_tfidf=tfidf.get_feature_names_out()

print('Feature Names(TF-IDF):\n',features_names_tfidf)
print()
print('TF-IDF Matrix:\n',x_tfidf.toarray())


Enter a statement:
	commonwealth bank cuts fixed home loan rates. community urged to help homeless youth commonwealth bank cuts fixed home loan rates.
commonwealth bank cuts fixed home loan rates.
45
community urged to help homeless youth commonwealth bank cuts fixed home loan rates.
84

Feature Names(TF-IDF):
 ['bank' 'commonwealth' 'community' 'cuts' 'fixed' 'help' 'home' 'homeless'
 'loan' 'rates' 'to' 'urged' 'youth']

TF-IDF Matrix:
 [[0.37796447 0.37796447 0.         0.37796447 0.37796447 0.
  0.37796447 0.         0.37796447 0.37796447 0.         0.
  0.        ]
 [0.23031454 0.23031454 0.32369906 0.23031454 0.23031454 0.32369906
  0.23031454 0.32369906 0.23031454 0.23031454 0.32369906 0.32369906
  0.32369906]]


In [ ]:
N-grams

In [4]:
import nltk
from nltk import ngrams
text='aba decides against community broadcasting licence'
tokens=nltk.word_tokenize(text)
#Generate bigrams
n=2
bigrams=list(ngrams(tokens,n))
print(f"Original text:{text}")
print()
print(f"Generated {n}-grams:")
for gram in bigrams:
    print(gram)

Original text:aba decides against community broadcasting licence

Generated 2-grams:
('aba', 'decides')
('decides', 'against')
('against', 'community')
('community', 'broadcasting')
('broadcasting', 'licence')


In [5]:
import nltk
from nltk import ngrams
text='aba decides against community broadcasting licence'
tokens=nltk.word_tokenize(text)
#Generate n-grams
n=3
ngrams=list(ngrams(tokens,n))
print(f"Original text:{text}")
print()
print(f"Generated {n}-grams:")
for gram in ngrams:
 print(gram)



Original text:aba decides against community broadcasting licence

Generated 3-grams:
('aba', 'decides', 'against')
('decides', 'against', 'community')
('against', 'community', 'broadcasting')
('community', 'broadcasting', 'licence')


In [6]:
import nltk
from nltk import ngrams
text='aba decides against community broadcasting licence'
tokens=nltk.word_tokenize(text)
#Generate n-grams
n=4
ngrams=list(ngrams(tokens,n))
print(f"Original text:{text}")
print()
print(f"Generated {n}-grams:")
for gram in ngrams:
 print(gram)

Original text:aba decides against community broadcasting licence

Generated 4-grams:
('aba', 'decides', 'against', 'community')
('decides', 'against', 'community', 'broadcasting')
('against', 'community', 'broadcasting', 'licence')


In [7]:
#generate n-grams with list comprehension
n=2
text='aba decides against community broadcasting licence'
tokens=nltk.word_tokenize(text)
ngrams=[tokens[i:i+n] for i in range(len(tokens)-n+1)]
print(f"Original text:{text}")
print()
print(f"Generated {n}-grams:")
for gram in ngrams:
 print(gram)


Original text:aba decides against community broadcasting licence

Generated 2-grams:
['aba', 'decides']
['decides', 'against']
['against', 'community']
['community', 'broadcasting']
['broadcasting', 'licence']


In [ ]:
Onehot encoding

In [8]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
text=['aba decides against community broadcasting licence','act fire witnesses must be aware of defamation',
      'ambitious olsson wins triple jump']
#step 1- tokens
tokens=[word for sent in text for word in sent.lower().split()]
#step 2- vocabulary
vocabulary=list(set(tokens)) # unique words in the text
#initialize encoder
encoder=OneHotEncoder(categories=[vocabulary],sparse=False)
#Perform the one-hot encoding
one_hot_encoded=[]
for sent in text:
    sent_encoded=[]
    for word in sent.lower().split():
        word_index=vocabulary.index(word)
        word_vector=np.zeros(len(vocabulary))
        word_vector[word_index]=1
        sent_encoded.append(word_vector)
        one_hot_encoded.append(sent_encoded)

for sent in one_hot_encoded:
    print(sent)

[array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0.]), array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.]), array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0.]), array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0.]), array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0.]), array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.])]
[array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0.]), array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.]), array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0.]), array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0.]), array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
   

In [9]:
sent[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0.])

In [10]:
sent[1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0.])

In [11]:
len(sent)

5

In [12]:
type(sent)

list

In [ ]:
Word2vec

In [4]:
!pip install gensim

Defaulting to user installation because normal site-packages is not writeable


In [4]:
pip install gensim

     ---------------------------------------- 24.0/24.0 MB 5.4 MB/s eta 0:00:00
  Using cached smart_open-6.4.0-py3-none-any.whl (57 kB)
Note: you may need to restart the kernel to use updated packages.


In [7]:
import gensim
from gensim.models import Word2Vec
from nltk.tokenize import word_tokenize
import nltk
#sample text
text=['freedom records net profit for third successive',
 'funds allocated for domestic violence victims',
 'funds allocated for youth at risk']
tokenized_text=[word_tokenize(sentence.lower()) for sentence in text]
#Train Word2vec model
model=Word2Vec(sentences=tokenized_text,vector_size=20,window=5,min_count=1,workers=4)
#Find word vectors
vector_youth=model.wv['youth']
vector_risk=model.wv['risk']
#similarity b/w words
similarity=model.wv.similarity('funds','successive')
print(f"Vector for 'youth':{vector_youth}")
print('='*100)
print(f"Vector for 'risk':{vector_risk}")
print('='*100)
print(f"Similarity b/w 'word' and 'successive':{similarity}")

Vector for 'youth':[-0.04309844  0.01832869  0.02594942  0.02870969  0.03733459 -0.03083838
  0.00552807  0.03023641 -0.01420025 -0.03086761 -0.00205112 -0.04184474
 -0.02800006  0.03552269  0.0167627   0.03612835  0.03400124  0.03765371
 -0.01894577 -0.00280903]
Vector for 'risk':[-0.00788826  0.00160686 -0.02070315 -0.03841344 -0.00754004  0.01234897
 -0.00444013  0.02766831 -0.01371489  0.01130033  0.02727897  0.04172977
 -0.0072687  -0.04604071  0.02185276  0.00285892  0.03720954 -0.00406641
 -0.01319207 -0.04376505]
Similarity b/w 'word' and 'successive':0.029164906591176987


In [6]:
from gensim.models import Doc2Vec
from gensim.models.doc2vec import TaggedDocument
from nltk.tokenize import word_tokenize
#sample text
documents=['freedom records net profit for third successive',
 'funds allocated for domestic violence victims',
 'funds allocated for youth at risk']
#Tokenize & tag documents
tagged_data=[TaggedDocument(words=word_tokenize(doc.lower()),
 tags=[str(i)]) for i,doc in enumerate(documents)]
print(tagged_data)


[TaggedDocument(words=['freedom', 'records', 'net', 'profit', 'for', 'third', 'successive'], tags=['0']), TaggedDocument(words=['funds', 'allocated', 'for', 'domestic', 'violence', 'victims'], tags=['1']), TaggedDocument(words=['funds', 'allocated', 'for', 'youth', 'at', 'risk'], tags=['2'])]


In [8]:
#Train Doc2vec model
model=Doc2Vec(vector_size=100,window=2,min_count=1,workers=5,epochs=20)
model.build_vocab(tagged_data)
model.train(tagged_data,total_examples=model.corpus_count,epochs=model.epochs)

In [9]:
vector_doc_1=model.infer_vector(word_tokenize("freedom records net profit for third successive"))

In [10]:
vector_doc_1

array([-3.2350098e-04, -7.9861179e-04, -3.7356646e-04,  4.6900677e-04,
        2.1767593e-04,  6.1079836e-04, -3.0939509e-03,  2.4871100e-03,
       -6.0130033e-04,  3.0301444e-03, -3.4139729e-03,  1.1866610e-03,
        1.5889225e-03, -2.2909276e-03, -5.1902269e-05,  6.6768070e-04,
        4.0777368e-03,  2.4608860e-03,  3.4108199e-03,  4.0113581e-03,
       -2.6875364e-03,  2.6701731e-03, -3.1437143e-03,  4.7604772e-03,
        3.1663741e-03, -4.1005113e-03,  7.5753947e-04,  8.3931972e-04,
       -3.2214404e-04,  4.0893694e-03,  3.7424481e-03, -1.8147351e-03,
        3.5270357e-03,  8.6473796e-04, -2.7394702e-03, -1.4964852e-03,
        4.5600985e-03,  3.7182102e-03,  4.4762864e-04, -3.8822377e-03,
        5.4201472e-04, -1.3621954e-03,  2.6261196e-03, -8.1568694e-04,
        3.8899891e-03, -3.1245635e-03,  9.5498259e-04,  3.8671680e-03,
       -4.5823581e-03, -4.8908186e-03, -4.6046795e-03,  3.7761454e-03,
       -1.7385056e-03,  9.6942611e-05,  1.9761352e-03,  2.9432636e-03,
      

In [11]:
#find the most similar document
similar_doc=model.docvecs.most_similar(positive=[vector_doc_1])
print(f"vector for 'freedom records net profit for third successive':{vector_doc_1}")
print()
print(f"Most similar document:{similar_doc}")


vector for 'freedom records net profit for third successive':[-3.2350098e-04 -7.9861179e-04 -3.7356646e-04  4.6900677e-04
  2.1767593e-04  6.1079836e-04 -3.0939509e-03  2.4871100e-03
 -6.0130033e-04  3.0301444e-03 -3.4139729e-03  1.1866610e-03
  1.5889225e-03 -2.2909276e-03 -5.1902269e-05  6.6768070e-04
  4.0777368e-03  2.4608860e-03  3.4108199e-03  4.0113581e-03
 -2.6875364e-03  2.6701731e-03 -3.1437143e-03  4.7604772e-03
  3.1663741e-03 -4.1005113e-03  7.5753947e-04  8.3931972e-04
 -3.2214404e-04  4.0893694e-03  3.7424481e-03 -1.8147351e-03
  3.5270357e-03  8.6473796e-04 -2.7394702e-03 -1.4964852e-03
  4.5600985e-03  3.7182102e-03  4.4762864e-04 -3.8822377e-03
  5.4201472e-04 -1.3621954e-03  2.6261196e-03 -8.1568694e-04
  3.8899891e-03 -3.1245635e-03  9.5498259e-04  3.8671680e-03
 -4.5823581e-03 -4.8908186e-03 -4.6046795e-03  3.7761454e-03
 -1.7385056e-03  9.6942611e-05  1.9761352e-03  2.9432636e-03
  4.8684194e-03 -4.0206783e-03 -1.5767500e-03 -2.6996050e-03
  2.6712797e-03  3.04033

C:\Users\Nirmala\AppData\Local\Temp\ipykernel_4128\812068268.py:2: DeprecationWarning: Call to deprecated `docvecs` (The `docvecs` property has been renamed `dv`.).
  similar_doc=model.docvecs.most_similar(positive=[vector_doc_1])
